# generate a list of dictionaries that containtains two keys: question and correct_answer
# the question is the question and the correct_answer is the correct_answer to the question
# the list is saved in a file called data.py

data = [{'question': 'What is the capital of France?', 'correct_answer': 'Paris'},
        {'question': 'What is the capital of Germany?', 'correct_answer': 'Berlin'},
        {'question': 'What is the capital of Spain?', 'correct_answer': 'Madrid'},
        {'question': 'What is the capital of Italy?', 'correct_answer': 'Rome'},
        {'question': 'What is the capital of Poland?', 'correct_answer': 'Warsaw'},
        {'question': 'What is the capital of Portugal?', 'correct_answer': 'Lisbon'},
        {'question': 'What is the capital of Greece?', 'correct_answer': 'Athens'},
        {'question': 'What is the capital of Sweden?', 'correct_answer': 'Stockholm'},
        {'question': 'What is the capital of Norway?', 'correct_answer': 'Oslo'},
        {'question': 'What is the capital of Denmark?', 'correct_answer': 'Copenhagen'},
        {'question': 'What is the capital of Finland?', 'correct_answer': 'Helsinki'},
        {'question': 'What is the capital of Iceland?', 'correct_answer': 'Reykjavik'},
        {'question': 'What is the capital of Ireland?', 'correct_answer': 'Dublin'},
        {'question': 'What is the capital of the Netherlands?', 'correct_answer': 'Amsterdam'},
        {'question': 'What is the capital of Belgium?', 'correct_answer': 'Brussels'},
        {'question': 'What is the capital of Luxembourg?', 'correct_answer': 'Luxembourg'},
        {'question': 'What is the capital of Switzerland?', 'correct_answer': 'Bern'},
        {'question': 'What is the capital of Austria?', 'correct_answer': 'Vienna'},
        {'question': 'What is the capital of Hungary?', 'correct_answer': 'Budapest'},
        {'question': 'What is the capital of Czech Republic?', 'correct_answer': 'Prague'},
        {'question': 'What is the capital of Slovakia?', 'correct_answer': 'Bratislava'},
        {'question': 'What is the capital of Slovenia?', 'correct_answer': 'Ljubljana'},
        {'question': 'What is the capital of Croatia?', 'correct_answer': 'Zagreb'},
        {'question': 'What is the capital of Bosnia and Herzegovina?', 'correct_answer': 'Sarajevo'},
        {'question': 'What is the capital of Serbia?', 'correct_answer': 'Belgrade'},
        {'question': 'What is the capital of Morrocro?', 'correct_answer': 'Rabat'},
        {'question': 'What is the capital of Algeria?', 'correct_answer': 'Algiers'},
        {'question': 'What is the capital of Tunisia?', 'correct_answer': 'Tunis'},
        {'question': 'What is the capital of Libya?', 'correct_answer': 'Tripoli'},
        {'question': 'What is the capital of Egypt?', 'correct_answer': 'Cairo'},
        {'question': 'What is the capital of Sudan?', 'correct_answer': 'Khartoum'},
        {'question': 'What is the capital of China?', 'correct_answer': 'Beijing'},
        {'question': 'What is the capital of India?', 'correct_answer': 'New Delhi'},
        {'question': 'What is the capital of Japan?', 'correct_answer': 'Tokyo'},
        {'question': 'What is the capital of South Korea?', 'correct_answer': 'Seoul'},
        {'question': 'What is the capital of North Korea?', 'correct_answer': 'Pyongyang'},
        {'question': 'What is the capital of Vietnam?', 'correct_answer': 'Hanoi'},
        {'question': 'What is the capital of Indonesia?', 'correct_answer': 'Jakarta'},
        {'question': 'What is the capital of Malaysia?', 'correct_answer': 'Kuala Lumpur'},
        {'question': 'What is the capital of Thailand?', 'correct_answer': 'Bangkok'},
        {'question': 'What is the capital of Philippines?', 'correct_answer': 'Manila'},
        {'question': 'What is the capital of Singapore?', 'correct_answer': 'Singapore'}
]